default_language_version:
  python: python3.12
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: uv run ruff check --fix --exit-zero
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff-format
        language: system
        entry: uv run ruff format
        types_or: [python, pyi, jupyter]
      - id: ty
        name: ty
        language: system
        entry: uv run ty check --exit-zero
        types: [python]
        pass_filenames: false
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
