data_loader:
  batch_size: 16
  device: cpu
  graph_const: radius
  knn_k: null
  num_workers: 0
  radius_ratio: 0.0001  # 0.075
  split:
    test_ratio: 0.15
    train_ratio: 0.7
    val_ratio: 0.15
group_id: 97
model:
  mem:
    inplace: true
  mp_layers:
  - act: relu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dim_inner: 128
    dropout: 0.0
    has_bias: true
    l2norm: false
    layer_type: ginconv
    normalize_adj: true
    pooling:
      n_clusters: 20
      type: mincut
    readout: mean
    use_batchnorm: false
  post_mp_layer:
    act: relu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dims:
    - 64
    - 32
    dropout: 0.0
    has_bias: true
    l2norm: false
    use_batchnorm: false
task:
  dataset_name: breast-cancer
  num_classes: 39
  type: node-classification
train:
  devices: auto
  early_stopping:
    metric: val_loss
    mode: min
    patience: 10
  enable_float32_matmul_precision: true
  lr_schedule:
    max_epoch: 2
    type: null
  max_epoch: 2
  optim:
    base_lr: 0.01
    momentum: 0.9
    optimizer: adam
    weight_decay: 0.0005
