data_loader:
  batch_size: 32
  device: cuda
  graph_const: knn
  knn_k: 20
  num_workers: 0
  radius_ratio: null
  split:
    test_ratio: 0.15
    train_ratio: 0.7
    val_ratio: 0.15
group_id: 9
model:
  global_pooling: max
  mem:
    inplace: false
  mp_layers:
  - act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dim_inner: 128
    dropout: 0.0
    has_bias: true
    l2norm: false
    layer_type: ginconv
    normalize_adj: false
    pooling:
      n_clusters: 10
      type: mincut
    readout: mean
    use_batchnorm: false
  post_mp_layer:
    act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dims:
    - 64
    - 2
    dropout: 0.0
    has_bias: true
    l2norm: false
    use_batchnorm: false
task:
  dataset_name: brca-ptnm-m
  num_classes: 2
  type: graph-classification
train:
  devices: auto
  early_stopping:
    metric: val_loss
    mode: min
    patience: 10
  enable_float32_matmul_precision: true
  lr_schedule:
    max_epoch: 1
    type: null
  max_epoch: 1
  optim:
    base_lr: 0.001
    momentum: 0.9
    optimizer: sgd
    weight_decay: 0.0005
