data_loader:
  batch_size: 8
  device: cuda
  graph_const: radius
  knn_k: null
  num_workers: 0
  radius_ratio: 0.05
  split:
    num_folds: 5
    split_index: 0
group_id: 1
model:
  global_pooling: mean
  mem:
    inplace: false
  mp_layers:
  - act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dim_inner: 16
    dropout: 0.0
    has_bias: false
    l2norm: false
    layer_type: sageconv
    normalize_adj: false
    pooling:
      n_clusters: 10
      type: dmon
    readout: mean
    use_batchnorm: true
  post_mp_layer:
    act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dims:
    - 16
    - 2
    dropout: 0.0
    has_bias: false
    l2norm: false
    use_batchnorm: true
task:
  dataset_name: spatial-vdj
  num_classes: 2
  type: graph-classification
train:
  devices: auto
  early_stopping:
    metric: split_0_val_loss
    mode: min
    patience: 10
  enable_float32_matmul_precision: true
  lr_schedule:
    max_epoch: 1
    type: null
  max_epoch: 1
  optim:
    base_lr: 0.1
    momentum: 0.9
    optimizer: adam
    weight_decay: 0.0005
