data_loader:
  batch_size: 32
  device: cpu # cuda:0
  graph_const: knn
  knn_k: 10
  num_workers: 0
  radius_ratio: 0.1
  split:
    test_ratio: 0.15
    train_ratio: 0.7
    val_ratio: 0.15
group_id: 1
model:
  global_pooling: mean
  mem:
    inplace: false
  mp_layers:
  - act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dim_inner: 16
    dropout: 0.0
    has_bias: false
    l2norm: false
    layer_type: sageconv
    normalize_adj: false
    pooling:
      n_clusters: 10
      type: dmon
    readout: mean
    use_batchnorm: true
  post_mp_layer:
    act: prelu
    bn_eps: 1.0e-05
    bn_momentum: 0.1
    dims:
    - 16
    - 1
    dropout: 0.0
    has_bias: false
    l2norm: false
    use_batchnorm: true
task:
  dataset_name: brca
  num_classes: 2
  type: graph-classification
train:
  early_stopping: null
  lr_schedule:
    max_epoch: 200
    type: null
  max_epoch: 200
  optim:
    base_lr: 0.1
    momentum: 0.9
    optimizer: adam
    weight_decay: 0.0005
